
SELECT * FROM public.foursquare_places 

UPDATE foursquare_places
SET tip='S'  WHERE category IN ('Accessories Stores',
								'Adult Boutiques',
								'Antique Shops',
								'Arts & Crafts Stores',
								'Auto Dealerships',
								'Auto Garages',
								'Automotive Shops',
								'Baby Stores',
								'Bagel Shops',
								'Bookstores',
								'Boutiques',
								'Bridal Shops',
								'Candy Stores',
								'Car Washes',
								'Cheese Shops',
								'Chocolate Shops',
								'Clothing Stores',
								'Comic Shops',
								'Convenience Stores',
								'Cosmetics Shops',
								'Delis / Bodegas',
								'Department Stores',
								'Dog Runs',
								'Electronics Stores',
								'Farmers Markets',
								'Fish Markets',
								'Flower Shops',
								'Food & Drink Shops',
								'Furniture / Home Stores',
								'Gas Stations',
								'Gift Shops',
								'Gourmet Shops',
								'Grocery Stores',
								'Health & Beauty Services',
								'Jewelry Stores',
								'Kids Stores',
								'Kuruyemişçis',
								'Lingerie Stores',
								'Liquor Stores',
								'Markets',
								'Mens Stores',
								'Miscellaneous Shops',
								'Mobile Phone Shops',
								'Mobility Stores',
								'Motorcycle Shops',
								'Music Stores',
								'Nail Salons',
								'Optical Shops',
								'Other Repair Shops',
								'Paper / Office Supplies Stores',
								'Pet Services',
								'Pet Stores',
								'Pharmacies',
								'Record Shops',
								'Salons / Barbershops',
								'Shoe Stores',
								'Shopping Malls',
								'Smoke Shops',
								'Smoothie Shops',
								'Sporting Goods Shops',
								'Supermarkets',
								'Toy / Game Stores',
								'Veterinarians',
								'Video Game Stores',
								'Womens Stores')
								
UPDATE foursquare_places
SET tip='DE'  WHERE category IN ('Cafés',
								 'Arepa Restaurants',
								 'Asian Restaurants',
								 'Austrian Restaurants',
								 'Bakeries',
								 'Bars',
								 'Beer Gardens',
								 'Bistros',
								 'Borek Places',
								 'Breakfast Spots',
								 'Breweries',
								 'Buffets',
								 'Burger Joints',
								 'Cafeterias',
								 'Cigkofte Places',
								 'Cocktail Bars',
								 'Coffee Shops',
								 'Comfort Food Restaurants',
								 'Creperies',
								 'Cupcake Shops',
								 'Dessert Shops',
								 'Diners',
								 'Doner Restaurants',
								 'Donut Shops',
								 'Fast Food Restaurants',
								 'Fish & Chips Shops',
								 'Fish Tavernas',
								 'Food',
								 'Food Courts',
								 'French Restaurants',
								 'Fried Chicken Joints',
								 'Frozen Yogurt Shops',
								 'Gastropubs',
								 'Gluten-free Restaurants',
								 'Halal Restaurants',
								 'Hookah Bars',
								 'Hot Dog Joints',
								 'Hotel Bars',
								 'Ice Cream Shops',
								 'Irish Pubs',
								 'Italian Restaurants',
								 'Kebab Restaurants',
								 'Kofte Places',
								 'Kokoreç Restaurants',
								 'Lebanese Restaurants',
								 'Lounges',
								 'Manti Places',
								 'Mediterranean Restaurants',
								 'Mexican Restaurants',
								 'Meyhanes',
								 'Middle Eastern Restaurants',
								 'Modern European Restaurants',
								 'Pastry Shops',
								 'Pide Places',
								 'Pie Shops',
								 'Pilavcıs',
								 'Pizza Places',
								 'Restaurants',
								 'Salad Places',
								 'Sandwich Places',
								 'Seafood Restaurants',
								 'Smoothie Shops',
								 'Snack Places',
								 'Soup Places',
								 'Steakhouses',
								 'Sushi Restaurants',
								 'Tantuni Restaurants',
								 'Tea Rooms',
								 'Turkish Home Cooking Restaurants',
								 'Turkish Restaurants',
								 'Vegetarian / Vegan Restaurants',
								 'Wine Bars',
								 'Wineries',
								 'Wings Joints')
								 
UPDATE foursquare_places
SET tip='E'  WHERE category IN ('Arcades',
								'Art Galleries',
								'Art Museums',
								'Arts & Crafts Stores',
								'Arts & Entertainment',
								'Athletics & Sports',
								'Bath Houses',
								'College Gyms',
								'College Theaters',
								'Comedy Clubs',
								'Concert Halls',
								'Dance Studios',
								'Event Spaces',
								'Gaming Cafes',
								'Golf Courses',
								'Gym Pools',
								'Gymnastics Gyms',
								'Gyms',
								'Gyms or Fitness Centers',
								'History Museums',
								'Hobby Shops',
								'Karaoke Bars',
								'Libraries',
								'Martial Arts Dojos',
								'Massage Studios',
								'Movie Theaters',
								'Multiplexes',
								'Museums',
								'Music Schools',
								'Music Venues',
								'Nightclubs',
								'Opera Houses',
								'Performing Arts Venues',
								'Pilates Studios',
								'Public Art',
								'Rock Clubs',
								'Salsa Clubs',
								'Social Clubs',
								'Spas',
								'Sports Clubs',
								'Theaters',
								'Yoga Studios')
								


UPDATE foursquare_places
SET tip='R'  WHERE category IN ('Aquariums',
								'Basketball Courts',
								'Basketball Stadiums',
								'Pools',
								'Pool Halls',
								'Soccer Stadiums',
								'Stadiums',
								'Street Art Installations',
								'Tennis Courts',
								'Tennis Stadiums',
								'Volleyball Courts',
								'Boarding Houses',
								'Botanical Gardens',
								'Buildings',
								'Forests',
								'Garden Centers',
								'Gardens',
								'Historic Sites',
								'Heliports',
								'Lighthouses',
								'Mosques',
								'Parks',
								'Pedestrian Plazas',
								'Playgrounds',
								'Scenic Lookouts',
								'Sculpture Gardens',
								'Skate Parks',
								'Theme Parks',
								'Trails',
								'Tunnels')
								
								
						
								 
								 
								 
								 
								 
								 
